[package]
name = "wasm_exp"
version = "0.1.0"
authors = ["kritzcreek <christoph.hegemann1337@gmail.com>"]
edition = "2018"

[dependencies]
wasmi = "0.5"
wabt = "0.8"
parity-wasm = "0.39"

[lib]
name = "simlwasm"
path = "src/lib.rs"

[[bin]]
name = "simlwasm"
path = "src/main.rs"
